export const botDownloadLinks: { [bot: string]: string } = {
  'ANB AIO': 'http://bit.ly/ANB-AIO-Setup',
  'ANB AIO V2': 'http://downloadsv2.aiobot.com/',
  BNB: 'http://bnba.io/download-bnb',
  'Balko (Mac - Zip)': 'http://rb.gy/6ya323',
  'Balko (Mac)': 'http://rb.gy/zagmsj',
  'Balko (Windows)': 'https://rb.gy/stcykc',
  'Balko Cookie Extension': 'https://s3.amazonaws.com/balkobot.com/BalkoExtension.zip',
  CyberAIO: 'https://rb.gy/4q2cck',
  Dashe: 'http://rb.gy/iceabf',
  EveAIO: 'https://rb.gy/lmzgya',
  'EveCaptcha (Mac)': 'https://rb.gy/4mnhky',
  'EveCaptcha (Windows)': 'https://rb.gy/enmpff',
  EveX: 'https://rb.gy/1uvr3k',
  'Ghost Cookie Extension': 'https://ghost.shoes/l/extension',
  'Ghost Phantom': 'https://ghost.shoes/l/phantom',
  'Ghost SNKRS': 'https://update.ghostaio.com/',
  'Ghost Wraith': 'https://ghost.shoes/l/wraith',
  'Ghost Wraith Chrome Extension': 'https://ghost.shoes/l/wraith-',
  HasteyIO: 'https://update.hastey.io/',
  Hawkmesh: 'http://download.hawkmesh.com/',
  Kodai: 'https://kodai.io/download',
  Latchkey: 'http://download.latchkeybots.io/',
  'MEK (Mac)': 'http://rb.gy/vfqugi',
  'MEK (Windows)': 'https://rb.gy/n3w6hc',
  'NSB (Mac)': 'https://nsb.nyc3.digitaloceanspaces.com/NSB-mac-latest.exe',
  'NSB (Windows)': 'http://rb.gy/imkhez',
  'PD Nike': 'https://swoosh.projectdestroyer.com/download',
  'PD Shopify': 'https://shopify.projectdestroyer.com/download',
  SoleAIO: 'https://drive.google.com/open?id=1GRpzE8Ofc2fY_ueNwvut4QjoKm4SdpGr',
  Splashforce: 'https://update.splashforce.io/',
  'TSB (Mac)': 'http://rb.gy/wmuofz',
  'TSB (Windows)': 'http://rb.gy/1zkoab',
  TheKickStation: 'https://rb.gy/dwkiln',
  'Tohru AIO': 'https://tohru.io/download',
  'Velox (Mac)': 'http://rb.gy/q3yb3s',
  'Velox (Windows)': 'https://rb.gy/fn5jz8',
  Wrath: 'https://download.wrathbots.co/'
}
