apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-access
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-access
subjects:
  - kind: ServiceAccount
    name: fleet-access
